spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=true
    username: root
    password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false



#fdfs
fdfs.connect_timeout=10
fdfs.network_timeout=30
fdfs.charset=UTF-8
fdfs.tracker_server=192.168.1.92:22122
fdfs.tracker_http_port=9092
fdfs.anti_steal_token=no